first_name = input('your first name: ')
last_name = input('your last name: ')
cpf = input('your CPF: ')
age = input('your age: ')
height = input('your height: ')
address = input('your address: ')
email = input('your email: ')
phone = input('your phone: ')
print('___________________________________________')
print(f'| NAME    | {first_name} {last_name}')
print(f'| CPF     | {cpf}')
print(f'| AGE     | {age}')
print(f'| HEIGHT  | {height}')
print(f'| ADDRESS | {address}')
print(f'| EMAIL   | {email}')
print(f'| PHONE   | {phone}')
print('___________________________________________')