nome = str(input('Digite algo: '))
print('O tipo primitivo desse arquivo é {}'.format(type(nome)))
print('Só tem espaços? {}'.format(nome.isspace()))
print('É um número? {}'.format(nome.isnumeric()))
print('É alfabético? {}'.format(nome.isalpha()))
print('É alfanumérico? {}'.format(nome.isalnum()))
print('Está em minúsculas? {}'.format(nome.islower()))
print('Está em maiúsculas? {}'.format(nome.isupper()))
print('Está capitalizada? {}'.format(nome.isprintable()))